# This is a basic workflow to help you get started with Actions

name: CacheBuster

# Controls when the workflow will run
on:
  # Executed: just after a new version of the site is deployed
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-pages
    
    env:
        CLOUDFLARE_ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
        CLOUDFLARE_EMAIL: ${{secrets.CLOUDFLARE_EMAIL}}
        CLOUDFLARE_API_KEY: ${{secrets.CLOUDFLARE_API_KEY}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Bust the cache on Cloudflare
      - name: Bust the cache on Cloudflare
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
           -H "X-Auth-Email: ${CLOUDFLARE_EMAIL}" \
           -H "X-Auth-Key: ${CLOUDFLARE_API_KEY}" \
           -H "Content-Type: application/json" \
           --data '{"purge_everything":true}'
